### ISSUE TITLE
Load java checkbox

### ISSUE THREAD

**Issue by lismateusz** [jyapayne/Web2Executable#98]
Hi,
I'm trying to create a stand-alone app for win32 sys (testing on Windows XP) along with node-java module. In GUI v0.3.1b for Linux (i'm working on Linux Mint 17.1 64) there is a checkbox "load java", but i can't figure out how it works. No metter it is checked or not, on require("java"); i'm getting : Uncaught Error: Cannot find module 'Java' in module.js:329 inside chromium devtool console. Is there a way to include node-java without compiling it on my own?

**Comment by jyapayne** [comment]
That option is a bit confusing. I should change it to "Load Java Applets", because that's what it allows you to do. See the [manifest](https://github.com/nwjs/nw.js/wiki/manifest-format#java).

As for getting the require to work, if you follow the node-webkit instructions on the [node-java repo readme](https://github.com/joeferner/node-java#installation-node-webkit), I'm sure you'll be able to get it working :)
